### ISSUE TITLE
Not Usable on High DPI Displays

### ISSUE THREAD

**Issue by lmaslanka** [M-Zuber/MyHome#120]
Running the application on a 4k monitor (3840x2160) the user interface is scrambled and most buttons are too small to use. The application does not scale with windows scaling settings.

![book_accounts_high_dpi_screenshot](https://cloud.githubusercontent.com/assets/129354/15862359/6cf015a4-2c9d-11e6-90ef-668e0d3e68a8.png)

**Comment by M-Zuber** [comment]
I will try to investigate this, high DPI and scaling are things I don't know too much about, so it might take some time to fix though. 

On an unrelated note out of curiosity  -  that screenshot doesn't exactly look like this app, is that due to work you've done?

**Comment by lmaslanka** [comment]
I downloaded a different app with the same name and mistaken it for this application. I just pulled the code and tested it and the application. It is perfectly fine at the 4k resolution. I apologise for the mistake. I am attaching a new screenshot of the correct application.


![monthly_flow_high_dpi_screenshot](https://cloud.githubusercontent.com/assets/129354/15894041/916a445e-2d51-11e6-8a8e-6ee587ccf5da.png)

**Comment by M-Zuber** [comment]
No worries. 
I really appreciate that you went the extra mile to test my app also!!

**Comment by M-Zuber** [comment]
Do you mind sending me the link to the first app you where using?

**Comment by lmaslanka** [comment]
Hello,

This is the site for the software; http://www.myhomesoftware.com/
