### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by M-Zuber** [M-Zuber/MyHome#50]
The `Readme` needs to include:
- [ ] Installation instructions
- [ ] Link to `Contributing.md`
- [ ] Feature List/
- [ ] Some free text about the project and other such stuff

**Comment by smwentum** [comment]
how do i log into the program for the first time? the keeps asking me for a database, username/password and i don't know what to say.

**Comment by M-Zuber** [comment]
Can you join me [here](https://gitter.im/M-Zuber/MyHome)

**Comment by smwentum** [comment]
sure

**Comment by M-Zuber** [comment]
Thank you for your interest @smwentum and I am looking forwards to some great contributions from you.

While the issue you raised helps clarify what kind of information is missing from the `README`,
in general it is better to open a new issue and then you (or I) can link it to any other appropriate issues.

**Comment by M-Zuber** [comment]
Feature list is not that urgent right now.
Will deal with it later.
The rest is good enough for now, I feel at least
