### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by M-Zuber** [M-Zuber/MyHome#51]
The `Contributing.md` should include the following:
- [x] Areas to focus on first
- [x] Coding guidlines

**Comment by M-Zuber** [comment]
- Coding Guidelines
 - [ ] Braces -with the opening brace on its own line.
 ```c#
 if (true)
 {
 }
 ```
 - [ ] Use `LINQ Extension Methods` over `query syntax`
 ```c#
 .Where(x => x); //Use this
 from y in z // Not this
 where y.x
 select y;
 ```
- Contributing
 - [ ] Work should be PR'ed to the `Development` branch -unless a specific branch exists.
 - [ ] Pull requests should be for an issue - if one doesn't exist _create it_.

**Comment by Jared314** [comment]
This should also include the process for feature requests and refactoring. Even though the process might be the same as issues, it would be good to be explicit about it.

**Comment by M-Zuber** [comment]
Committed 667a4bf81890048c5aad67ffd36e4fee9c3bbbb7.
Any thoughts?

**Comment by M-Zuber** [comment]
At this point it is done.
What is left is too get into the habit of reviewing it at set intervals
