### ISSUE TITLE
Changlog

### ISSUE THREAD

**Issue by M-Zuber** [M-Zuber/MyHome#52]
Should forks be encouraged (to be written in `Contributing`) to keep a running file that they do  not send in for the pull request of their own changes?

**Comment by dodiaraculus** [comment]
Do you meen like a log?

**Comment by M-Zuber** [comment]
Yes, based off the concepts [here](http://keepachangelog.com/).
But closing the issue as this is for sure not the responsibility of contributors, although they can be encouraged.
