### ISSUE TITLE
Using Sqlite instead of MySql?

### ISSUE THREAD

**Issue by Jared314** [M-Zuber/MyHome#62]
From reading through the codebase, it looks as if MySql primarily serves as local data storage. What about using something more self-contained and file centric, like [Sqlite](http://www.sqlite.org/)?

In addition to not requiring a separate database server, it could also function as a full-featured backup/export format.

**Comment by M-Zuber** [comment]
I'll look into it. Thank you for the input.

**Comment by M-Zuber** [comment]
@Jared314 My dream is too be able to set up `mobile` and `web` endpoints. While that is a long way in the future it doesn't look it would work with  `Sqlite`, because once we get that far it will be one database with users/server with db per user.

Do you think that there is enough to be gained in switching now -if we would switch back in the future?

**Comment by Jared314** [comment]
> Do you think that there is enough to be gained in switching now -if we would switch back in the future?

As both MySql and Sqlite are SQL database engines with ADO.NET libraries, the biggest differences would be switching from `MySqlConnection` to `DbConnection`, and changing the Login form into a open file dialog.

The work involved, in generalizing the database access, would also pay off in generally refining the data layer to better support future changes, like a service endpoint.

**Comment by M-Zuber** [comment]
And considering that in any case the `Dal` should probably be moved to `EF`, it would go well together to switch it all at once.
Before starting on this, I would like to get a `Contributing.md` set up first.
I hope to get too that over the next few days.

**Comment by Jared314** [comment]
If you would like to see what this might look like. I modified a branch, that I was experimenting with, to use SQLite.

https://github.com/Jared314/MyHome2013/tree/multiple-database-support

A sample database file is included: [`Sql Files/base.sqlite`](https://github.com/Jared314/MyHome2013/blob/multiple-database-support/Sql%20Files/base.sqlite)

**Comment by M-Zuber** [comment]
Thanks. I hope to properly look it over in the next day or two.
How different do you think the code would be if the `DAL` was using `Entity Framework`?

**Comment by M-Zuber** [comment]
I have created a [branch](https://github.com/M-Zuber/MyHome2013/tree/Multiple-db-support) for this.
When you get a chance please open a pull request to it.
(as far as issues go this one will do)
