### ISSUE TITLE
Technologies to use for testing

### ISSUE THREAD

**Issue by M-Zuber** [M-Zuber/MyHome#65]
- Unit Tests
 - MSTest ([Stackoverflow](http://stackoverflow.com/questions/tagged/mstest))

- Integration Tests
 - Are they different from Feature Tests?

- Feature Tests
 - [SpecFlow](http://www.specflow.org/)

**Comment by M-Zuber** [comment]
If you have a suggestion of a testing library to use, please open an issue and comment with a link here.
ex.
> Consider using library `x` for `y tests`. see #--

**Comment by Jared314** [comment]
Take a look at [xUnit](http://xunit.github.io/) for unit testing.
