### ISSUE TITLE
No exception thrown for missing database 

### ISSUE THREAD

**Issue by smwentum** [M-Zuber/MyHome#94]
I was able to use the program, but not able to save data. Moreover the program didn't tell me that it wasn't saving. Here are the error logs. I was working off  the master branch if that helps.

logs

**Comment by smwentum** [comment]
i guess that doesn't work including them in the glitter chat.

**Comment by M-Zuber** [comment]
![](http://media3.giphy.com/media/Z9ZgpdHuhpjVu/giphy.gif)

**Comment by M-Zuber** [comment]
[Here is the error file](https://github.com/M-Zuber/MyHome/files/13619/errors.txt)
As you can see, it does throw the errors that the tables do not exist. The issue is that the errors are simply swallowed.
Care to try and find out why?
Some things that come to mind:
- Empty catches
- Catches that log but do not rethrow
- Other implementation details?

**Comment by M-Zuber** [comment]
One more thing - any work you do should please be done on the `Development` branch. TIA

**Comment by smwentum** [comment]
Hey

  I think i am getting closer to figuring this out. I see that in the login.cs. lines (62-70) checks to see if all of the boxes are non-empty which is fine, but assuming that it just assumes everything else will work. I would guess that the solution is that i would need to actually check to see if the database is created.

**Comment by smwentum** [comment]
should i create a new AccountingDataContext object and go from there?

**Comment by M-Zuber** [comment]
It might be better to abstract and use a method like `TestConnection`
This way the ui has less to know about how the data is used. 
For an example, look at the code on `master` to see how the connection was tested.

**Comment by M-Zuber** [comment]
Once you have such a method, if the use supplied enough information you just have to set the property on the form to the result of the call to `TestConnection`

**Comment by smwentum** [comment]
hi 

 Ok i think i was in the wrong branch, and not really working on the error. :-(. I think i see the problem in the connection manager, to test to see if the database is working. the program open and closes the connection, I think the problem is that either it needs to check to see if the necessary tables are in there and if not create them, or throw an exception.

**Comment by M-Zuber** [comment]
The correct branch is `Testing`. Currently, in that branch no check is made.
You can use the code in `master` as a starting point to get an idea of how an abstracted connection test can be made.
It sounds like a good idea to add the following checks:
- Can connect to the database
- The tables exist

Any other checks you would add?

**Comment by M-Zuber** [comment]
As far as creating the tables if they are not found - I would like to hold out on that for a bit

**Comment by smwentum** [comment]
Are you sure the testing branch is working? I can get the program to work on the master and development branch, but when i open the testing branch and try to create an expense the program freezes up and after a min gives an error of not being able to connect to the database.

**Comment by M-Zuber** [comment]
hmmm..
What database are you using?
IRCC `master` and `development` use `MySql` while `testing` uses `mmsql`

Care to dump the error log here or gitter?

**Comment by M-Zuber** [comment]
As mentioned in `gitter`, there is now a fix on the `unit-tests` branch to let it work with `mmsql`
I also hope to make a writeup in the wiki explaining the process of setting things up.
Feel free to ask any questions

**Comment by M-Zuber** [comment]
>A side note on this whole thing

@qchouleur updated the project to use `EntityFramework.CodeFIrst`. There should be a step of model building that happens at compilation or on first run that creates the database if it does not exist. It is possible that it would be better to focus on fixing that

**Comment by M-Zuber** [comment]
The project has a stable release with EF Code First.
So this should no longer be an issue at all.

Thank you for reporting this.
