### ISSUE TITLE
DataBase 

### ISSUE THREAD

**Issue by cezarant** [M-Zuber/MyHome#95]
Hi Friends, i'm interessed to triage issues in project. But i don't find the sql file to create database. 
Anybody help-me?

**Comment by M-Zuber** [comment]
Everything you need should be [here] (https://github.com/M-Zuber/MyHome/tree/Testing/Sql%20Files). 

Please work on the Testing branch for now.
For now you need mmsql installed and then to run the script manually.

**Comment by cezarant** [comment]
Thanks!
